### ISSUE TITLE
Why not use http.HTTPStatus?

### ISSUE THREAD

**Issue by ghost** [IlianIliev/Status-Codes-Site#1]
Why do you enumerate the HTTP Status Codes by hand? You could use [`http.HTTPStatus`](https://docs.python.org/3/library/http.html#http.HTTPStatus).

**Comment by IlianIliev** [comment]
Hi @lutzhorn and first please accept my apologies, I have somehow missed any notification for this issue and I just saw it.

Now on topic - unfortunately `http.HTTPStatus` does not support all status codes currently available in the project. For example 444 taken from https://en.wikipedia.org/wiki/List_of_HTTP_status_codes. I know that some of those are not part of the official HTTP spec but when the site was made there were requests for those.

Greetings,
Ilian
